### ISSUE TITLE
Please make it useful within a frame

### ISSUE THREAD

**Issue by barbudo2005** [pratikabu/scrolltotop#110]
I use EZlinkpreview but Scroll to top not play within a frame.

Thank you in advance

**Comment by pratikabu** [comment]
Enabling this extension for iFrames poses bigger problems than actually solving. I had to purposefully disable it long back to make the extension work properly.

**Comment by barbudo2005** [comment]
Thank you

**Comment by pratikabu** [comment]
@barbudo2005 closing this issue. in case you've further questions feel free to reach out. thanks
