### ISSUE TITLE
Is scrolltotop ever coming back to macOS 10.15.x Safari 13.x ?

### ISSUE THREAD

**Issue by DJay-X** [pratikabu/scrolltotop#116]
Is scrolltotop ever coming back to macOS 10.15.x Safari 13.x ?
😕

**Comment by pratikabu** [comment]
hi @DJay-X, The extension for Safari now requires a new framework to be written on Xcode. Honestly speaking I've not tried it yet. Also, to host it on Safari extension platform I'll need to buy Apple Developer subscription every year.

**Comment by DJay-X** [comment]
Thanks for your reply. I understand. But such a shame. I loved your work and still miss it under Safari 13.x. :(
However, I am dependent on the use of the Safari browser, for various reasons.

**Comment by pratikabu** [comment]
@DJay-X, I already have my thoughts to make it work for Safari as well. Will try to do some more research soon.
Will be closing this issue out. Stay safe :)
