### ISSUE TITLE
Auto-Hide issue + Suggestions:

### ISSUE THREAD

**Issue by LucianAndries** [pratikabu/scrolltotop#119]
Hello!

FIRST: Dude, the extension is friggin awesome!!!!!! 💓

Please change how "Auto-Hide" works.
Make the button always be invisible, until the mouse cursor is over it. When you take the cursor from it, it becomes invisible again. NO 5 seconds wait...
Make it show up when the cursor is over it, NOT by scrolling the page. It's frustrating, not showing up until you start scrolling... That is wrong! 😭
Change that, or add it as additional modifier settings.

Also:
Please add more sizes for the arrows. Or let us set its size like you did with the position on screen.
And please let us export the settings into a .json file. Copy and pasting is impractical.

Thank you!

**Comment by LucianAndries** [comment]
Also @pratikabu :

1. Please make the Arrow NOT rotate back up, if we scroll down. ONLY rotate the Arrow back up, once it is ON the bottom!! Just one pixel away from the bottom, the Arrow should still point down.

2. And please add the Single Arrow options, to the Dual Arrow options, as well.
-Add the Control Options to Dual Arrow, as well.
-Add the Icon Size to Dual Arrow, as well. But make everything more resizable. Even the small arrow, is too big.....! 😭

PLEASE fix all these issues, and my other #120 thread. Please!
Btw, donation... 👍

**Comment by pratikabu** [comment]
> Please make the Arrow NOT rotate back up, if we scroll down. ONLY rotate the Arrow back up, once it is ON the bottom!! Just one pixel away from the bottom, the Arrow should still point down.

Did you try smart direction mode?
![image](https://user-images.githubusercontent.com/470973/81740991-7000df80-9463-11ea-9581-fd71fa5b7258.png)

**Comment by pratikabu** [comment]
> Btw, donation... 👍
Thanks for that.

> And please add the Single Arrow options, to the Dual Arrow options, as well.
> -Add the Control Options to Dual Arrow, as well.
> -Add the Icon Size to Dual Arrow, as well. But make everything more resizable. Even the small arrow, is too big.....! 😭
I know that is quite a mess. But that's a good suggestion to add control options for dual arrow. The icon size can't be manipulated simply, there are many factors I'll have to factor in.

**Comment by pratikabu** [comment]
> Please change how "Auto-Hide" works.
> Make the button always be invisible, until the mouse cursor is over it. When you take the cursor from it, it becomes invisible again. NO 5 seconds wait...

I've a solution for you. Did you try setting the transparency of the addon? You can use any existing `Visibility Behavior` from the settings menu and update the addon's transparency value to minimum.

![image](https://user-images.githubusercontent.com/470973/81742797-45645600-9466-11ea-9656-8af758374f82.png)

If you want it completely invisible then as well you should be able to do that by tweaking the config json. Otherwise I can add that as an option in the next release.

What you say?

**Comment by LucianAndries** [comment]
Hey.

-Yeah, "smart direction mode" is even worse. For me anyway...
-And transparency, pfff.....no. I want it completely gone from the screen, until the mouse cursor is over it, and then it is fully visible. I don't want to see through it, I don't want to see it at all.
-Why is changing the size difficult? You are already doing it, now just add an even smaller version, or let us set the number of pixel size. Also, add this for both 1 and 2 arrows.

And this:
"Please make the Arrow NOT rotate back up, if we scroll down. ONLY rotate the Arrow back up, once it is ON the bottom!! Just one pixel away from the bottom, the Arrow should still point down".

I came from another similar extension where it was almost great and had everything... The only issue it had, it was conflicting with other extensions. 😡
So if you want to know how some of its stuff works, here, install it and dissect it:
https://chrome.google.com/webstore/detail/scroll-to-top-button/chinfkfmaefdlchhempbfgbdagheknoj?utm_source=chrome-ntp-icon

Good luck.

**Comment by pratikabu** [comment]
Hey @LucianAndries, the YouTube issue is tracked here #92.

**Comment by LucianAndries** [comment]
> Hey @LucianAndries, the YouTube issue is tracked here #92.

Umm, ok...? But I have absolutely no clue what is that all about... :|

**Comment by schipht** [comment]
Hi @pratikabu,

Can you add double click option to toolbar icon for go to bottom of page instead of one click?

Also can you add this icon to extension?
https://www.flaticon.com/free-icon/up-and-down-arrows_1148842

**Comment by pratikabu** [comment]
@LucianAndries I believe your issues were addressed as part of last release that I did. If you still have any more points. Please raise another ticket.

@schipht browser extension framework does not allow double click on toolbar icon. See [this document](https://developer.chrome.com/docs/extensions/reference/api/action) for details. Also, any custom image can be added using Base64 encoding on Options page.

Screenshot of the options page.
<img width="658" alt="image" src="https://github.com/pratikabu/scrolltotop/assets/470973/177caee4-16ba-42a0-ad89-534914d60aa5">

I'll be closing this issue. Let me know if you've any questions.

**Comment by pratikabu** [comment]
@LucianAndries I re-read your comments and here are my comments for them.

- I fixed the Smart Direction Mode. Give it a try.
- To make the icon completely invisible you can export the settings and then tweak this config `"iconTransparency": 0`. This will make the icon to go completely invisible. You will have to import the settings again after you've tweaked it.
- The reason why changing the size is difficult is that we've to worry about dimensions of all the icons. I've raised another ticket #170 to address it.

Thanks again for using it.
