### ISSUE TITLE
BIG Cosmetic Filter Issue:

### ISSUE THREAD

**Issue by LucianAndries** [pratikabu/scrolltotop#120]
Hello again...

I've just discovered a really BIG issue. It happens on Some sites, but it happens.

Your extension is headbutting with "uBlock Origin" for some reason.
When the Arrow is visible, everything on the page disappears. And if it's hidden, everything on the page is shown correctly.

It is when I disable Cosmetic Filtering on uBlock, that the page is completely loaded with the Arrow visible as well...
So, can you please look into this and fix it?

- The website is: https://www.wcostream.com/

- uBlock store link: https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm

If this happens only with the filters I am using, then I attached the Backup file for uBlock, to this thread. Importing that in uBlock, will give it the filters I use, and start to download them.

I hope you can fix it, because there are websites where I just can't disable the filters. 😭

Thank you!
[my-ublock-my-backup.txt](https://github.com/pratikabu/scrolltotop/files/4613687/my-ublock-my-backup.txt)

**Comment by LucianAndries** [comment]
Also @pratikabu :

1. Please make the Arrow NOT rotate back up, if we scroll down. ONLY rotate the Arrow back up, once it is ON the bottom!! Just one pixel away from the bottom, the Arrow should still point down.

2. And please add the Single Arrow options, to the Dual Arrow options, as well.
-Add the Control Options to Dual Arrow, as well.
-Add the Icon Size to Dual Arrow, as well. But make everything more resizable. Even the small arrow, is too big.....! 😭

PLEASE fix all these issues, and my other #120 thread. Please!
Btw, donation... 👍

**Comment by LucianAndries** [comment]
@pratikabu 

Hope you're taking a look at this one too. 😭

**Comment by pratikabu** [comment]
I tried replicating your steps but couldn't replicate.

Installed the uBlock extension.

Applied your filters.
![image](https://user-images.githubusercontent.com/470973/82163784-cc546c80-9872-11ea-80bb-2415efee0225.png)

Opened https://www.wcostream.com/ website. The icon still shows up.

![image](https://user-images.githubusercontent.com/470973/82163749-b646ac00-9872-11ea-9d6c-0e897cd852b6.png)

**Comment by pratikabu** [comment]
@LucianAndries, send me what you see in screenshots. Will try to co-relate if I can.

**Comment by LucianAndries** [comment]
@pratikabu 

Hey!

Hmm, you are right, it's working for me too, now.
Maybe the filter that was blocking it, updated and fixed it... Or it must've been a browser/site issue, coz I cleared all the cookies and cache today, as well....

Whatever it was, glad it's over. Thank you for trying.
Then this ticket is closed. :)

There's still ticket 119, though. :P
