### ISSUE TITLE
Ability to hide Context Menu Item

### ISSUE THREAD

**Issue by barbudo2005** [pratikabu/scrolltotop#129]
It is  posible to add an option to not show the Context Menu Item?

**Comment by pratikabu** [comment]
I thought about that earlier but thought it might not be required. I’ll add this though. Thanks for raising.

**Comment by pratikabu** [comment]
Added a new Advanced Option to show/hide the Context Menu entry.

![image](https://user-images.githubusercontent.com/470973/82950570-23d99300-9f6b-11ea-9290-7f4a09466d34.png)


You've to click on the "Show More Settings" button to show this option.
![image](https://user-images.githubusercontent.com/470973/82950478-fe4c8980-9f6a-11ea-97fd-832b1eaf5f97.png)


Closing this issue. This will be released in 4.9.1 milestone.
