### ISSUE TITLE
Scroll to top in Forums

### ISSUE THREAD

**Issue by barbudo2005** [pratikabu/scrolltotop#135]
The Vivaldi Forum has continuous pagination, so you don't have to click next page.

If you are in the fourth page, when you click "scrroll to top" it goes to the top of the fourth page, not to the absolute top. So you have to click 4 times to go to the absolute top.

Tank you very much in advance.

**Comment by pratikabu** [comment]
@barbudo2005, I don't see the pagination applies automatically on the forum.

I was trying this url: https://forum.vivaldi.net/category/34/vivaldi-browser-for-macos?lang=en-US

What url did you try it on? Do you've any other tool which does automatic pagination for you?

**Comment by barbudo2005** [comment]
You have to sign-in to have the option of using infinite scroll:

![image](https://user-images.githubusercontent.com/59028314/84458344-34605d80-ac3b-11ea-8073-4965ae5fc68e.png)

**Comment by pratikabu** [comment]
Hi @barbudo2005, I looked further on this and can conclude that, the reported behavior is coming from the site itself.
Looks like this page does pagination in both directions. When you are down > 3 pages and then if you want to come up it fetches the results again and points the first of post of that page as the rendering element.

I can replicate that behavior with normal scrolling too. Don't this Scroll To Top extension can solve that behavior, this is something Vivaldi has to fix or change.

Sorry for no help on this. I'll close this issue next week, unless you've any further question.
