### ISSUE TITLE
Behavior with Frames

### ISSUE THREAD

**Issue by barbudo2005** [pratikabu/scrolltotop#137]
I use EZLinkPreview to view pages in frames, so I don't open many tabs.

The icons of Scroll to Top are visible on the frame, but they don't scroll the frame.

So, Is possible to maintain the icons underneath the frame?

**Comment by barbudo2005** [comment]
I do it changing the z-index of the frame.

**Comment by pratikabu** [comment]
hi @barbudo2005 I guess this question was similar to this #110.
I'll try after installing EZLinkPreivew extension to see if I can support that usecase or not.

**Comment by pratikabu** [comment]
EZLinkPreivew extension is no more active, I cannot check on this. Closing this issue.
@barbudo2005
