### ISSUE TITLE
Scroll to top does not work properly on Firefox 79.0

### ISSUE THREAD

**Issue by matsuda0707** [pratikabu/scrolltotop#138]
After updating to Firefox 79.0, the scroll to top become not to work properly, such as , setting position, speed, transparency and etc. became default(?). For example I set the position to the horisontally right/vertically middle, the scroll to top icon appeares on the bottom/right or middle/left! This problem occurs on Firefox 79.0 on Windows10, not on MacOS. Also the scroll to top works well on the Google chrome and Opera Vivaldi, and other Crome derivertives.

**Comment by pratikabu** [comment]
Thanks for the explanation, I'll try to take a look at it.

**Comment by matsuda0707** [comment]
Thanks for your reply, pratikabu !
This problem occurs when updating from 4.9 to 4.9.1.
_ downloaded 4.9 from the page (https://addons.mozilla.org/ja/firefox/addon/scroll-to-top/versions/), and installed it without updating. 4.9 works well without any problem as the previous version, but when I updated to 4.9.1, the same problems arose ( no icon, reset to initial,etc). 
This problem occurs only on version 4.9.1 on Firefox 79.0 (Windows10), but no problem on other browser such as Google chrome, Vivaldi,etc. and also browsers on MacOS.

**Comment by pratikabu** [comment]
Thanks for the detailed explanation. Did you try installing directly the 4.9.1 version?
Firefox might have changed something in their later version. I'll have to see what is causing this, coz I released 4.9.1 back in June beginning. Not sure why this problem popping up now.

https://github.com/pratikabu/scrolltotop/releases/tag/v4.9.1

**Comment by matsuda0707** [comment]
I already tried 4.9.1 from official page through add-on manager.
From my experience,

1)4.9 works well as the previous version.
2)When updating to 4.9.1, the scroll arrow icon suddenly disappear, setting is set to default, reset of icon position, etc.
3)Then go back to 4.9, everything begins work normally.

**Comment by pratikabu** [comment]
That's strange, I upgraded my laptop to a mac. I'll setup a VM for Windows.

**Comment by Maxxxxxx** [comment]
I had FF 79.0 - then 80 and now have 80.0.1 and STT broke Outlook mail.  I could not open the program unless/until I disabled STT.

Ended up using a different UP arrow.  Today I had the same problem w/email. Cannot access website.  
This time I went into safe mode.  That ended up causing a sh**storm.  All is better now.
Not using anything to return to top.  VERY inconvenient.

Anybody else ever come to you with this issue?

Thank you.

**Comment by pratikabu** [comment]
I'm sorry for the inconvenience, but I'm not sure what could be causing issues with Outlook. There could be some additional addon which might be causing issues.

Sad to see you go though.

**Comment by Maxxxxxx** [comment]
I thought these programs specifically were problematic.

There was no additional addon which contributed.  So, no clue.  

I am trying it again.

Thank you for your very prompt response.

**Comment by pratikabu** [comment]
Since I was not able to replicate the issue that you were facing, we can try some screensharing session sometime if that works for you. Maybe this weekend.

**Comment by Maxxxxxx** [comment]
Let me work with the two addons that I have and see if I can pinpoint something further.
Thank you for your most generous offer.
