### ISSUE TITLE
Scroll Arrows have disappeared in Firefox 80.0.1 (64-bit)

### ISSUE THREAD

**Issue by gunnora** [pratikabu/scrolltotop#139]
My up and down scroll arrows have disappeared in the last few days.

Firefox 80.0.1 (64-bit)
Windows 10 Home 64-bit (10.0, Build 18363) (18362.19h1_release.190318-1202)

**Comment by pratikabu** [comment]
Hi @gunnora, did you try checking your settings? You can try resetting them or try re-installing this addon. Let me know if that works.

**Comment by gunnora** [comment]
I have tried both actions, neither helped.

________________________________

**Comment by gunnora** [comment]
I still am not getting the scroll arrows. At this point I have:

Firefox 80.0.2 (64-bit)
Windows 10 Home 64-bit (10.0, Build 18363) (18362.19h1_release.190318-1202)

**Comment by pratikabu** [comment]
Thank you for providing more details. I tried with similar configuration, but was able to use it properly.
Do you have any other addon which is causing issues?
<img width="975" alt="image" src="https://user-images.githubusercontent.com/470973/97522970-0cb22d80-196f-11eb-994a-e7e2450f94a2.png">

**Comment by gunnora** [comment]
I finally tried switching to a different icon, in this case the red circle with two upwards pointing chevrons, and that works find. It doesn't work with the default blue button, which seems odd. Nevertheless, the functionality is what I am after, and it's decided to work, so I am happy.

**Comment by pratikabu** [comment]
Glad it worked, not sure though why it didn't work with default icon.

I'll close the issue.
