### ISSUE TITLE
New Facebook Design Problem

### ISSUE THREAD

**Issue by SPWGitHub** [pratikabu/scrolltotop#140]
Scroll to Top works on the news feed and group pages, but nowhere else.

[Facebook](https://facebook.com)

**Comment by pratikabu** [comment]
hi @SPWGitHub, can you tell me where does it not work. These days I'm rarely using Facebook.

**Comment by pratikabu** [comment]
Sorry for the long delay in replying.

**Comment by SPWGitHub** [comment]
Hi:

It doesn't show up on friends lists, which is where I spend most of my time.

*Steve Wilson*
*      (͡° ͜ʖ ͡°)*

**Comment by pratikabu** [comment]
that's like internal div. this only works on main page scroll bar, if that is outside of iFrame.

**Comment by SPWGitHub** [comment]
It's not outside of iFrame. It's within the main scroll bar.
Create a custom friends list and replicate the problem.

**Comment by SPWGitHub** [comment]
Never mind, you're correct.  My mistake.  Sorry.

**Comment by pratikabu** [comment]
Though the addon works fine on the list of your friends. The behavior you are talking about happens when you click on this icon, right?

<img width="282" alt="image" src="https://user-images.githubusercontent.com/470973/106347466-6125bb80-6284-11eb-960e-771e51ad21e4.png">
