### ISSUE TITLE
Android Support

### ISSUE THREAD

**Issue by JeffCarpenter** [pratikabu/scrolltotop#142]
This extension would be a godsend on mobile!

**Comment by pratikabu** [comment]
hi @JeffCarpenter it used to be there but Firefox pulled the plug and now only few addons are supported on Firefox for mobile.

Only these extensions are currently supported on Firefox Android.
https://addons.mozilla.org/en-US/android/

I've reached multiple times to Firefox to get my addon recommended but they never responded. So, I'm not very much hopeful they will do anything for this extension to be listed on Android.

**Comment by pratikabu** [comment]
As I can't take action on this, I'll be closing this issue.
