### ISSUE TITLE
[Broken website] lavas-project.github.io/pwa-book/chapter06/1-manifest-json.html

### ISSUE THREAD

**Issue by Higurashi-kagome** [pratikabu/scrolltotop#143]
This is a great extension, thanks a lot!👋

But it seems that scrolltotop can't work well on [1-manifest-json.html](https://lavas-project.github.io/pwa-book/chapter06/1-manifest-json.html). I mean, when trying to scroll by clicking scrolltotop extension icon, this page will not scroll.

<details>
<summary>This is my options</summary>

![image](https://user-images.githubusercontent.com/51501079/103470007-6c7de800-4da7-11eb-9f69-4330a1be251f.png)

</details>

Further, I found it also can't scroll by clicking icons inside the page because there is no icon generated on the page although the `Show Icons on Page` option is enabled：

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/51501079/103470088-83710a00-4da8-11eb-99cd-1b53ef8aa565.png)

</details>

**Comment by pratikabu** [comment]
Hi @Higurashi-kagome, apologies for replying late. I saw this website and found that this website is uses absolute positioning of the content div the content is not actually expanding the browser scroll. I'm afraid I cannot do any logic to make it work on this site.

**Comment by Higurashi-kagome** [comment]
I see, anyway, still thanks for your extension, its' really useful. @pratikabu

**Comment by pratikabu** [comment]
Thank you for the kind words. @Higurashi-kagome
