### ISSUE TITLE
Google Docs Bug

### ISSUE THREAD

**Issue by purevertigo** [pratikabu/scrolltotop#167]
Does not work when using Google Docs in edit or preview mode.

**Comment by pratikabu** [comment]
Hi @purevertigo, thanks for using Scroll To Top. Scroll To Top works when the page has top level scrolling. Complex pages like Google Docs renders the content inside a div container which is not scrollable by the page level scrolling, so this extension cannot detect that. I'll be closing this ticket, but feel free to comment on it if you still have further questions.
