### ISSUE TITLE
Scroll To Top: all features not visible in Mavericks

### ISSUE THREAD

**Issue by JohnDohe** [pratikabu/scrolltotop#20]
I just installed Mavericks and now my beloved "Scroll To Top" isn't showing all the functions I was used to.  I can only see the up/down curly arrows to speed to the top or bottom of a page.  I need to be able to go up/down one screen at a time.  Fix?

**Comment by pratikabu** [comment]
I hope Scroll To Top is working fine for you, closing this issue. Thanks.
