### ISSUE TITLE
Doesn't work everywhere

### ISSUE THREAD

**Issue by markfriedman** [pratikabu/scrolltotop#21]
OSX 10.9.1, Safari 7.1, Scroll to Top 4.4

It works on the majority of sites I visit and I couldn't think of why it wouldn't function on game's forum site:  http://forums.z2.com/viewtopic.php?f=360&t=59078

If it will help, I'll post additional sites where it doesn't work as expected as I come across them.

This is a wonderfully useful utility.  Thanks for developing and maintaining it.

**Comment by pratikabu** [comment]
hi Mark,

Just revisited this issue and found that its working good for the site you mentioned.
I visited you site also, its amazing.. Keep up the great work you doing.

Thanks
