### ISSUE TITLE
Use right icon

### ISSUE THREAD

**Issue by anticlyde** [pratikabu/scrolltotop#23]
Hi,

i've checked scroll to top settings page, and you definatly haven't right icon.
check this screen
https://www.dropbox.com/s/cm6z3erfo77rsmr/icon%20screen%20_scroll%20to%20top.png
code:
https://www.dropbox.com/s/suu45p2ocfx3z86/icon%20%2B%20settings%20_scroll%20to%20top.txt

base64 encoded by string:
iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAKVJREFUeNrs1TEOgzAMheEUygHYszBz/zP0BHRgYaAbG2sWPHioUCUStU4T6f+kt4CF/FAEzgEAAAAAAAAAAFTmljA7Sryky7DXIpliBtuE5YeE+W/1+qK2q8Em8oHDH06HjxlqCj7eXQkFdo0ZywJB8tCE2gqEt8WDZQmrAs/T0dn1WhUFZsn64fqq94ou8LpYctaZn7kbfLu9y6jk/wAFkMMhwACIwxlRrd9x+AAAAABJRU5ErkJggg==

take it
hold it
love it

_____
yours Alex aSS

**Comment by anticlyde** [comment]
hi pratikabu,

i replying late too,

i want to take you an icons for scroll to top,
it simple and beauty.
https://www.dropbox.com/sh/nbn07ybmsa9t0ks/AABz35Xh8YdA1TrKm_GFQS43a?dl=0
icon itself:
https://www.dropbox.com/s/q97y7exl32vq9tb/stripe_2_3.png?dl=0

experemented with another variations and choose that.

what is my point of share icons?
i can choose simple icon by default.

**Comment by pratikabu** [comment]
hi Alex,
I hope you are using this icon with "Use My Icon" setting. Will try to include your suggestion in the OOTB list of icons.
Thanks
