### ISSUE TITLE
Icon does not appear in gmail

### ISSUE THREAD

**Issue by orschiro** [pratikabu/scrolltotop#24]
Hi there, 

Thanks a lot for your amazing extension!

However, I noticed that the icon does not appear in Gmail.

Is there anything you can do about it to make it working with Gmail?

Thanks for listening

**Comment by PikMaster** [comment]
Hi. Sorry for resurrecting the old thread, I just found your extension when Gmail annoyed me to the point where I started searching for solution. I can see you released 4.9.1 now, do you have any ideas how to implement it in Gmail? Maybe via some opt-in case, where you can always attach the button to a given frame on a given site?

**Comment by pratikabu** [comment]
Long back I removed the configuration to go into the inner frame. It had way too many cons than pros. I don't remember the specifics now. Where exactly you want to scroll? Inside an email?

https://developer.chrome.com/extensions/content_scripts#frames

**Comment by PikMaster** [comment]
Yes, in the long email thread, I want to scroll back to the start to see what labels are applied to the conversation.
Moving my hand out of my mouse and pressing the Home key to do that is distrupting my workflow.
Thanks.

On 7 December 2020 23:36:06 GMT, Pratik Soni <notifications@github.com> wrote:
>Long back I removed the configuration to go into the inner frame. It
>had way too many cons than pros. I don't remember the specifics now.
>Where exactly you want to scroll? Inside an email?
>
>https://developer.chrome.com/extensions/content_scripts#frames
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/pratikabu/scrolltotop/issues/24#issuecomment-740246963

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by pratikabu** [comment]
Gmail shows the content in another DIV tag and this tag. This addon can only work at the body tag level overflow. Sorry won't be able to help.

<img width="531" alt="image" src="https://user-images.githubusercontent.com/470973/106375857-7585b900-6355-11eb-89aa-2ec622e079a5.png">
