### ISSUE TITLE
Conflict with another extension when displaying tall images

### ISSUE THREAD

**Issue by AndyP2002** [pratikabu/scrolltotop#26]
I'm using "Scroll to Top 4.3.1" with Firefox (25.0.1 - I'm not updating any more!)

Scroll to Top seems to be conflicting with: "Zoom Page 10.7"

I'm having a problem when I follow a link to an image that is very tall. With Zoom to Top installed, the image is shown extremely compressed and squashed into a 'postage stamp'.

Here's an example: http://i.imgur.com/VjvCqNf.jpg
That should be a stack of 6 normal-shaped screenshots in a single, tall 534x2444 pixels jpg image.
When I open it in a new browser tab or window, it is usually zoomed out to show the entire image (pic No.1)

![scrolltotop1](https://cloud.githubusercontent.com/assets/8184678/3606516/b85d13b6-0d37-11e4-889f-cfca67016edb.jpg)

....and I can then single left click on it to zoom in so the text is readable (pic No.2).

![scrolltotop2](https://cloud.githubusercontent.com/assets/8184678/3606519/c4a4d712-0d37-11e4-97ef-4a3662f962a7.jpg)

However, with "Scroll to top" installed, the first image display I get is vertically squashed into a small square on screen (about 1 inch on each side - pic No.3) with the "Zoom Page" display in the menu bar indicating 300%.

![scrolltotop3](https://cloud.githubusercontent.com/assets/8184678/3606523/d9de1c60-0d37-11e4-9c31-d3479389744f.jpg)

 If I then click on the image, it re-draws even smaller (Zoom Page indicates 100%).

If I disable "Zoom Page" everything works as normal, but I find that such a useful add-on, I do not want to lose it.

**Comment by pratikabu** [comment]
Closing this defect as I'll be releasing the Webextension for Firefox.

**Comment by AndyP2002** [comment]
Wow, who was that "together person" 3 years ago? 
After 3 years of using Android and Windows 10, I can barely string a sentence together now.
Thanks for your perseverence!
