### ISSUE TITLE
scroll to top mobile doesn't work on firefox 35.0 on android.

### ISSUE THREAD

**Issue by shiomr** [pratikabu/scrolltotop#35]
after version up to ff35.0 on android 4.1.2, scroll to top mobile doesn't work.
I love it and i want use.

**Comment by pratikabu** [comment]
hello, I've seen that its not working on FF Android version, will update the version soon.
will keep you posted.

Pratik

**Comment by pratikabu** [comment]
hello I've looked into the issue and found that Firefox for Android version 34 has introduced a problem which is causing this issue and blocking this addon to work.
Firefox team is working on this issue, we've to wait until we hear from them.
https://bugzilla.mozilla.org/show_bug.cgi?id=1107240

**Comment by shiomr** [comment]
Thank you ,Mr. pratikabu ! I'm happy to hear the progress.I wait them.

**Comment by pratikabu** [comment]
Hello there, Firefox Android v39 has solved the problem for us. This addon works great now. :+1:

**Comment by shiomr** [comment]
It's great. thank you your work.
