### ISSUE TITLE
Options not working on Firefox 36?

### ISSUE THREAD

**Issue by AndyP2002** [pratikabu/scrolltotop#36]
I have been using Firefox v35.0.1 (Portable version) successfully with Scroll to Top.

I have just installed Firefox v36.0.1 on the same laptop, and am having a few problems.

1. When I go to the options page none of my preferences are saved. (no buttons are highlighted green)
2. On the options page, the scrolling speed text is there, but the slider is missing.
3. None of the buttons at the bottom (Show more settings, Restore to defaults, Import/Export, and Support me) are working.
4. So I cannot access advanced settings like the Transparency slider and alternative icons.
5. Presumably because of the issues with the preferences page, I cannot set the Arrow icon to have the small up/down arrows beside it.

V36 screenshot:
![scrolltotop ffv36](https://cloud.githubusercontent.com/assets/8184678/6361128/7c882f0c-bc77-11e4-9ff4-bec86a3c6fa3.jpg)
(cannot access advanced settings)

V35 screenshots:
Basic:
![scroll to top 1 - firefox v35](https://cloud.githubusercontent.com/assets/8184678/6361273/b3cca35c-bc78-11e4-82f8-631973693938.jpg)
Advanced:
![scroll to top firefox v35 adv1](https://cloud.githubusercontent.com/assets/8184678/6361289/c1e3f6f2-bc78-11e4-9854-15a67d1fd514.jpg)
![scroll to top firefox v35 adv2](https://cloud.githubusercontent.com/assets/8184678/6361296/c9c7d758-bc78-11e4-8503-1df73d150ff8.jpg)

I have a few different add-ons installed in the v36 Firefox, but nothing particularly unusual.
I can list them if you feel it would help.

**Comment by pratikabu** [comment]
Hi Andy,

You seems to using an older version of Scroll To Top. Kindly download the
latest version from:
https://addons.mozilla.org/en-US/firefox/addon/scroll-to-top

This problem is fixed in 4.5.1 version.

Thanks

**Comment by AndyP2002** [comment]
Thank you, that sorted it straight away
    
    Best regards
    Andy
    
    On 25/02/2015 02:56, Pratik Soni wrote:
    
    Hi Andy,
      
      You seems to using an older version of Scroll To Top. Kindly
      download the
      latest version from:
      https://addons.mozilla.org/en-US/firefox/addon/scroll-to-top
      
      This problem is fixed in 4.5.1 version.
      
      Thanks
      On 25-Feb-2015 4:20 am, "AndyP2002"
      <notifications@github.com> wrote:
      
      > I have been using Firefox v35.0.1 (Portable version)
      successfully with
      > Scroll to Top.
      >
      > I have just installed Firefox v36.0.1 on the same laptop, and
      am having a
      > few problems.
      >
      > 1. When I go to the options page none of my preferences are
      saved. (no
      > buttons are highlighted green)
      > 2. On the options page, the scrolling speed text is there,
      but the
      > slider is missing.
      > 3. The Transparency text and slider are both missing.
      > 4. None of the buttons at the bottom (Show more settings,
      Restore to
      > defaults, Import/Export, and Support me) are working.
      > 5. Presumably because of the issues with the preferences
      page, I
      > cannot set the Arrow icon to have the small up/down arrows
      beside it. V36: [image:
      > scrolltotop ffv36]
      >
<https://cloud.githubusercontent.com/assets/8184678/6361128/7c882f0c-bc77-11e4-9ff4-bec86a3c6fa3.jpg>
      >
      > —
      > Reply to this email directly or view it on GitHub
      > <https://github.com/pratikabu/scrolltotop/issues/36>.
      >
      —
        Reply to this email directly or view
          it on GitHub.
      
        
          
          
        
        
      
    
    
  



	
		
			
				
			
		
		
			
				This email is free from viruses and malware because avast! Antivirus protection is active.

**Comment by pratikabu** [comment]
happy to hear that.. closing this issue.. :+1:
