### ISSUE TITLE
Option to Hide Exit Icon

### ISSUE THREAD

**Issue by stilbon** [pratikabu/scrolltotop#37]
I would like another "Control Option" that would hide the "exit" icon displayed when reading. 

I frequently use the "scroll down one page" and then "scroll up one page" icons to read and then review what I just read.  

The cursor can wander because I get so involved with what I am reading.  More often than I would like, I inadvertently click the “exit” icon, which is really not what I want to do since it so distracting.  

BTW, “Scroll To Top” is an exceptional extension!

**Comment by pratikabu** [comment]
hi Stilbon, I'll keep this in mind for the new release.

Thanks

**Comment by pratikabu** [comment]
Going to add option on the Options page to select one of the below shown configurations.

![image](https://user-images.githubusercontent.com/470973/77837050-1b5f0a80-712a-11ea-94a0-ac6a2d324a18.png)
