### ISSUE TITLE
Icon not showing on github pages

### ISSUE THREAD

**Issue by akileez** [pratikabu/scrolltotop#40]
using Safari Desktop. Something must have recently changed with github css because it was working a couple of hours ago. Other pages no problem. If you need more info, let me know what you need.

**Comment by pratikabu** [comment]
hi Keith, I tried it on GitHub page and it did work. Here is the link on which I tried. https://github.com/pratikabu/scrolltotop/blob/master/base/pratikabu-stt.css

Can you share the link on which you saw it is not working.

**Comment by akileez** [comment]
[here](https://github.com/jonschlinkert/fs-utils/blob/master/index.js). This is what I see:
![scrolltotop](https://cloud.githubusercontent.com/assets/4314979/9376164/63c869b0-46d7-11e5-907a-b08c021ba68a.png)

Just a box where the arrow icon should be. I don't even get the box with the link you displayed.

**Comment by pratikabu** [comment]
aah.. seems like it is specific for Safari, as I'm able to see it in Chrome on Windows.
Will check it on Safari 5 as I don't have Mac :(

![image](https://cloud.githubusercontent.com/assets/470973/9376199/7eae58a2-4727-11e5-9674-fb8e81a40768.png)

**Comment by akileez** [comment]
ok then. I will look through the code and see what I can find on my end. thanks for confirming.

**Comment by akileez** [comment]
ok, got this from the inspector:
[Error] Refused to load the image 'safari-extension://net.sf.users.pratikabu.stt-E5WB5T4538/c6835bb8/icons/pratikabu-stt-bottom-16.png' because it violates the following Content Security Policy directive: "img-src 'self' data: assets-cdn.github.com identicons.github.com www.google-analytics.com collector.githubapp.com *.githubusercontent.com *.gravatar.com *.wp.com".

**Comment by akileez** [comment]
sorry for the spew but here are all the errors:

```sh
[Error] Refused to execute inline script because it violates the following Content Security Policy directive: "script-src assets-cdn.github.com collector-cdn.github.com". (index.js, line 0)

[Error] Refused to load the image 'safari-extension://net.sf.users.pratikabu.stt-E5WB5T4538/c6835bb8/icons/pratikabu-stt-32-2.png' because it violates the following Content Security Policy directive: "img-src 'self' data: assets-cdn.github.com identicons.github.com www.google-analytics.com collector.githubapp.com *.githubusercontent.com *.gravatar.com *.wp.com".

[Error] Refused to load the image 'safari-extension://net.sf.users.pratikabu.stt-E5WB5T4538/c6835bb8/icons/pratikabu-stt-clear-16.png' because it violates the following Content Security Policy directive: "img-src 'self' data: assets-cdn.github.com identicons.github.com www.google-analytics.com collector.githubapp.com *.githubusercontent.com *.gravatar.com *.wp.com".

[Error] Refused to load the image 'safari-extension://net.sf.users.pratikabu.stt-E5WB5T4538/c6835bb8/icons/pratikabu-stt-settings-16.png' because it violates the following Content Security Policy directive: "img-src 'self' data: assets-cdn.github.com identicons.github.com www.google-analytics.com collector.githubapp.com *.githubusercontent.com *.gravatar.com *.wp.com".

[Error] Refused to load the image 'safari-extension://net.sf.users.pratikabu.stt-E5WB5T4538/c6835bb8/icons/pratikabu-stt-bottom-16.png' because it violates the following Content Security Policy directive: "img-src 'self' data: assets-cdn.github.com identicons.github.com www.google-analytics.com collector.githubapp.com *.githubusercontent.com *.gravatar.com *.wp.com".

[Error] Refused to load the image 'safari-extension://net.sf.users.pratikabu.stt-E5WB5T4538/c6835bb8/icons/pratikabu-stt-settings-16.png' because it violates the following Content Security Policy directive: "img-src 'self' data: assets-cdn.github.com identicons.github.com www.google-analytics.com collector.githubapp.com *.githubusercontent.com *.gravatar.com *.wp.com".

[Error] Refused to load the image 'safari-extension://net.sf.users.pratikabu.stt-E5WB5T4538/c6835bb8/icons/pratikabu-stt-bottom-16.png' because it violates the following Content Security Policy directive: "img-src 'self' data: assets-cdn.github.com identicons.github.com www.google-analytics.com collector.githubapp.com *.githubusercontent.com *.gravatar.com *.wp.com".

```

**Comment by pratikabu** [comment]
oh but in this case, it should be a problem on every page. Has the addon stopped working on all the pages?

One bad thing that Apple has done it unifying the Safari developer program with other developer programs. Now I've to pay $99 per year if I want to list this addon on the new platform, which makes no sense as I don't own a Mac and I cannot download new Safari browser on my Windows machine.

The above errors might be coming due to new policies in the Safari addon development process. I'll try my level best to replicate it in my local and also if they still allow me refer the development docs.

I'm sorry if I'm confusing you, but I found you techie enough to share my thoughts on losing my Safari users. :)

**Comment by akileez** [comment]
Problem ONLY appears with github pages. All other sites I viewed after midnight East Coast US experienced no problems. Only github pages. That is why I thought github may have changed their css files.
I totally understand where you are coming from and its not life shattering for me. I can easily use google chrome for github viewing. You may close this issue. I am satisfied with your reply.

**Comment by pratikabu** [comment]
that's very kind of you.. thank you..
