### ISSUE TITLE
Scroll speeds

### ISSUE THREAD

**Issue by MarkEllard** [pratikabu/scrolltotop#41]
Hello, I like the extension. I would like it able to scroll slower if thats possible?
Also it does not show on microsoft sites - sharepoint, visual studio online.

thanks
Mark

**Comment by pratikabu** [comment]
Hi Mark,

Let me see if I can add some reader mode in this tool, so that when you hover on it. It will go smoothly and slowly.

Thanks

**Comment by pratikabu** [comment]
Going to add more speed option.

**Comment by pratikabu** [comment]
Added 6-7 additional speed modes. Closing the issue
