### ISSUE TITLE
Losing settings every now and then

### ISSUE THREAD

**Issue by Danita** [pratikabu/scrolltotop#42]
Sometimes when restarting the PC or after a crash, or Firefox update, Scrolltotop loses its settings and I have to restore them from a saved json. I cannot seem to replicate the problem because its sporadic. Any ideas?

**Comment by pratikabu** [comment]
Hi Daniela,

This is an existing Firefox issue. It happens sometime with Firefox.

Let me know if you've any questions.

Thanks
Pratik

**Comment by pratikabu** [comment]
I've submitted a new version of this addon after building it with latest Firefox JPM framework. I hope to see this problem resolved after this. Also, you can use the Export/Import feature of this addon and save your configuration so next time if it loses you can import it again.

Hope this helps, I'm closing this defect. Let me know if you see this behavior again.
