### ISSUE TITLE
Not working with Firefox-Nightly version 48

### ISSUE THREAD

**Issue by SpyroRyder** [pratikabu/scrolltotop#43]
What the title says.  Although I have other extensions installed I don't think it's a clash because disabling them doesn't do anything and the link to the settings page also doesn't work

**Comment by pratikabu** [comment]
hi, I've submitted a new version of this addon by building it with latest Firefox JPM framework. I hope once this is approved your problem should be resolved.

**Comment by pratikabu** [comment]
I'll be closing this issue, anticipating that it will be resolved once the latest version is available.
Let me know if you've any concerns.
