### ISSUE TITLE
It does not work in SeaMonkey 2.40

### ISSUE THREAD

**Issue by wvxwxvw** [pratikabu/scrolltotop#44]
It does not work in SeaMonkey 2.40

Make please support SeaMonkey 2.40. After the conversion is not possible to change the settings. I to use by default. :)

**Comment by pratikabu** [comment]
hi, I can provide you one working version of the extension for SeaMonkey. The only thing is that you cannot customize the extension as the option page does not load on SeaMonkey. I've no idea why it is behaving like that. SeaMonkey does not has any documentation and developer console to deal with this situation.

Will it be fine with you?

**Comment by wvxwxvw** [comment]
Hi, sorry my GoogleEnglish. 

> I to use by default.

Thank you. But converted extension of me  running. Those. it works, but configure it can not. I use the default settings. Its no good.

**Comment by pratikabu** [comment]
hi, Sorry I didn't get. do you want me to send you the converted extension?

**Comment by wvxwxvw** [comment]
No. Such at me is. With no work settings.  :)

**Comment by pratikabu** [comment]
Okay got it. Also, the settings are not working in Sea Monkey, its an internal Firefox API through which I fetch the settings. Seems like Sea Monkey yet does not support that.
I'll launch it for Sea Monkey as well once they support it.
For now closing the issue.
