### ISSUE TITLE
Settings page continues to load

### ISSUE THREAD

**Issue by progkix** [pratikabu/scrolltotop#48]
Firefox 45.0.1, Scroll To Top 4.5.5

The settings page continues to load every time I start / restart Firefox

**Comment by pratikabu** [comment]
hi, can you try reinstalling it. Firefox is not maintaining settings properly.
Also, do store your setting by clicking on Import/Export settings button on the options page.
Once the Web Extensions are available in Firefox this problem will be completely gone.
Do let me know if that solves the issue.
