### ISSUE TITLE
Jumping arrow position

### ISSUE THREAD

**Issue by burnuser** [pratikabu/scrolltotop#58]
After automatic  Updating Scroll to Top to the the new WebExtension Version 4.7 on Firefox (55.0.3 - 64 Bit) and reconfiguring the settings like I have them used before (Vertical: Middle, Horizontal: Right, Always Show, Dual Arrow, Vertical Arrangement, Horizontal Offset: 0) the arrows are shown on an opened webpage as expected.
But on mouseover the arrows are jumping horizontally a bit to the middle.
The scrolling by clicking on the new positioned arrows works, but the jumping is very irritating.
After reloading the page, it starts again. Arrows are shown as configured ... and jumping on mouseover.

**Comment by pratikabu** [comment]
hi, i tried with the same configuration and it woks good for me. Can you tell me which site were you trying to access on which you saw this behavior.

Thanks

**Comment by pratikabu** [comment]
Also, can you try re-installing the addon. I tried multiple things but couldn't reproduce this issue.

**Comment by burnuser** [comment]
I saw this behaviour on every site, I tried (see attached screenshots from https://www.golem.de/)

I also tried it with re-installing and additionally with a fresh Firefox install (PortableApps) and Scroll To Top as the one and only add-on ... same problem.

But it seems to occur only with Dual Arrow.

It works always correct with single arrow.

And it seems, that the problem has something to do with the change from single arrow to dual arrows which does not have the same configuration options like single arrow (Control Options, Auto Hide, Icon Size)

For example, if I have changed the Icon Size to small for single arrow. After selecting dual arrow, the arrows does not jump, but shrink on mouseover.

In other dual arrow configuration sequences (the order of steps - in single arrow followed by dual arrow - seems to be relevant) the arrows change from horizontal to vertical arrangement on mouseover.

And finally I have found a working configuration sequence with dual arrow, vertical arrangement: changed icon size to small at single arrow, then change to dual arrow and using Icons recommended for Horizontal Arrangement (solution works not with Icons for Vertical Arrangement).

I think the problem is caused by the sequential mix-up of the different configuration options for single and dual arrows. Maybe a change in UI and programming to a consistent set of selectable options for single AND dual arrow would be a good idea for the overall usability of your great add-on ... and as solution for the problems described above.

![pageloaded](https://user-images.githubusercontent.com/32030147/30629000-cb34d236-9dd9-11e7-9b2c-5439c699c618.jpg)
![aftermouseover](https://user-images.githubusercontent.com/32030147/30629010-d83fae9c-9dd9-11e7-93e5-007770bafdd6.jpg)

**Comment by hdd60311** [comment]
use 57beta3(64bit) and have same problem here.

**Comment by xbkingx** [comment]
Same problem. It appears on mouseover, the element adds "width: 96px".

From:
`<div id="pratikabuSTTDiv" class="pratikabusttdiv-no-print" style="top: 50%; right: 20px; opacity: 1; display: block;">`

To:
`<div id="pratikabuSTTDiv" class="pratikabusttdiv-no-print" style="top: 50%; right: 20px; opacity: 1; display: block; width: 96px;">`

The outer element (bounding box) expands to the left, the inner element (actual images) aligns left, and boom.  96px is the width of the horizontally aligned arrows AND the single arrow with extra controls. So, the controls take up the new 48px to the left of the arrow and it doesn't appear to move.

If the simple right double arrow is selected, you're passing the width for right vertical double with pager, horizontal double, or the single arrow with pager. 

Also, for the single arrows, you're setting them to float:right, while the vertical double arrows are not set explicitly.

Single arrow:
`<img id="pratikabuSTTArrowUp" style="float: right; opacity: 0.415333; cursor: pointer; width: 48px; height: 48px; transform: rotate(180deg);" class="pratikabuSTTImg pratikabuSTTBlackAndWhite" src="moz-extension://71c69491-2d40-4bd0-aa59-a952ebeb2bd6/icons/pratikabu-stt-48-32.png">`

Double:
`<img id="pratikabuSTTArrowUp" style="display: block; opacity: 0.415333; cursor: pointer;" class="pratikabuSTTImg pratikabuSTTBlackAndWhite" src="moz-extension://71c69491-2d40-4bd0-aa59-a952ebeb2bd6/icons/pratikabu-stt-48-32.png">`


That should easily be enough to track down the bug. Cheers!

**Comment by paul1149** [comment]
If I recall, there was an extension update yesterday, and I've just connected that with this behavior starting last night. On mouseover, the arrows jump maybe 20 pixels to the left. I use a vertical arrangement, but the first (blue) vertical arrows, and they are in the middle of the page vertically, and on the right. I'm in vivaldi 1.13, stable channel, up to date. Great extension, btw.

**Comment by paul1149** [comment]
Here's a screen cap.

https://drive.google.com/open?id=1NNDiaSiZEY1SdaDkjWr1fkc4ZKKDOzvM

**Comment by pratikabu** [comment]
hi @paul1149 , thanks for the video this helps. Can you ping me which URL are you accessing this?
I tired testing this but everything was looking good on normal sites. It might be specific sites which are causing issue.

hi @xbkingx, thank you for the detailed explanation. I'll look into it and try to accommodate it in the next release. I'm not touching the core JS file [pratikabu-stt.js](https://github.com/pratikabu/scrolltotop/blob/master/base/pratikabu-stt.js) for the releases these days as I'm dealing with browser level changes. I'll have to focus on this file to add the expected behavior.

Thanks

**Comment by pratikabu** [comment]
I'm able to replicate the issue which you are facing on the site which you've mentioned. But this doesn't look like any upgrade issue. It should have been like this forever.

I'll take a look at it once I'm done with my office work today.

**Comment by pratikabu** [comment]
And I could be wrong it could be due to some mess up in the settings as well. I'll keep you posted whatever my findings are. As I'm now able to replicate this issue on stackoverflow.com as well.
I don't know somehow a width of 96px is getting added to the div tag.

**Comment by xbkingx** [comment]
@pratikabu Thanks much. I isolated the problem and a workaround for anyone with this right now, so hopefully the stuff below helps:

Cause: Previously selecting to have the pager appear is remembered when switching to a layout without the pager option, including both dual arrow settings. 
Solution: Reset the pager option value to the value for 'None' when selecting dual arrows .

Steps to reproduce: Select single arrow layout with pager (either "simple" or "with pager"). Select Dual Arrows and test.
Steps to work around: Perform steps to reproduce (giggity), but select "none" for pager before selecting Dual Arrows.

I noticed that the width goes from blank to 48px or 64px depending on which pager option is selected.

For vertical double arrows, it manifests as jumping to the left (aligned left, width changed, moves to fill space). For horizontal arrows it manifests as switching to the vertical layout (width goes from calculated in script, to arrow+pager, pager is smaller than arrow, so it reflows to the next line).

**Comment by pratikabu** [comment]
great observation @xbkingx. This certainly should be due to the migration of settings. I'll have to check what exactly went wrong.

**Comment by pratikabu** [comment]
Aah finally I found what is the root cause of all these issues. I made a change in 4.7 in which I changed what settings are sent to the actual core js file. Earlier I was restricting the settings based on the dual arrow or single arrow selection. Now I'm sending all the settings back to the core js file. It is completely 
 affecting the dual arrows.

There were two settings it was affecting one is the known issue, the other one is related to smart direction mode. Both of them are fixed.

I've made changes to handle all the conditions.

I would request you guys to review it once with this pull request https://github.com/pratikabu/scrolltotop/pull/70. Or else, I would merge this by this weekend and provide a release for all 3 browsers.

I've also identified one issue with options page where the settings are not getting changed, I suspect it is due to the latest jQuery update which I provided. I'll take a look at it aswell before this weekend and provide a combined release.

**Comment by paul1149** [comment]
Great work bro.

**Comment by pratikabu** [comment]
also thanks to @burnuser, I should have paid attention a lot earlier to fix this issue.

**Comment by pratikabu** [comment]
okay I've fixed the options page issue as well in #71

**Comment by xbkingx** [comment]
Awesome work. Thanks for looking into this. I'll try to test it tomorrow and let you know.
And thanks for this great add on. It has saved me countless hours that would have been spent navigating submenus and is the first thing I install on a new build.

**Comment by xbkingx** [comment]
@pratikabu Tested out the latest changes and it looks like you fixed it. Thanks much!

**Comment by pratikabu** [comment]
Hi @xbkingx @paul1149 , I just uploaded all the fixes to a temporary addon you can test it there.

https://chrome.google.com/webstore/detail/scroll-to-top-test/faekplikfggcblgchgadnklakifbehfm/related?utm_source=chrome-ntp-icon

**Comment by pratikabu** [comment]
@xbkingx looks like you already tested it. Thanks

**Comment by paul1149** [comment]
Just installed the test build. Looking very good. Great job. Please let us know when the regular extension is updated, so we can enable it again. Thanks!

**Comment by pratikabu** [comment]
Alright, have released the latest version. It should be live in sometime.

**Comment by hdd60311** [comment]
Seems that the version in firefox AMO is still 4.7.2?

**Comment by pratikabu** [comment]
Firefox is also approved now and 4.7.5 is now available. Cheers
