### ISSUE TITLE
Feature Request: Ability to exclude scrolltotop on incompatible websites

### ISSUE THREAD

**Issue by keithxyxy88** [pratikabu/scrolltotop#62]
Hi -

I love scrolltotop, but on the Canadian Walmart site the up/down icon appears gigantic, takes up the whole page:
https://www.walmart.ca/en
Anywhere on the page I click I get the "to top" or "to bottom" action.

I don't go to Walmart Canada much, I'd be happy if I could just have Scrolltotop be excluded from the website.  (Walmart.com seems fine.  It is Walmart Canada that is the issue for me.)

So that is my request:  the ability to exclude scrolltotop on incompatible websites.

Thanks.

- Keith

**Comment by pratikabu** [comment]
Hi Keith,

You can maintain a list of excluded pages. You can add walmart.ca there. Go to settings page and click on "Show More Settings" and follow the screenshot below.

![image](https://user-images.githubusercontent.com/470973/34430364-dfc9cb4a-ec29-11e7-8845-4c656f0b7319.png)

I'll be closing this issue, you can comment back if it doesn't work for you.

Cheers
Pratik
