### ISSUE TITLE
Using responsive web design for setting page

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [pratikabu/scrolltotop#66]
Since porting to WebExtensions, this extension works fine on Firefox for Android. However the settings page does not optimized for mobile devices, so I suggest recontrusting the style of this page using responsive web design.

**Comment by pratikabu** [comment]
Hi,

Though I've now removed the support for Android for the STT extension as I developed a [separate extension for mobile](https://addons.mozilla.org/en-US/android/addon/scroll-to-top-mobile/).
But you are right that the options page should be responsive. I've to anyhow redesign the options page as Chrome is going to remove the support to open the options page in a new window. I'll try to consider it their.

Thanks
Pratik

**Comment by pratikabu** [comment]
I'll see how it looks with the new changes that I've done. If I've to make it complete responsive then it will be big work.

**Comment by KrasnayaPloshchad** [comment]
Yeah, this is fixed in 4.8.
