### ISSUE TITLE
Selected settings are not saved

### ISSUE THREAD

**Issue by ineuw** [pratikabu/scrolltotop#68]
In FF 57.0.4 Windows, After setting the preferences (it is indicated that they were saved), nothing happens - no icon on screen. On reopening the Options, all previously selected settings are gone.

**Comment by pratikabu** [comment]
It seems like some specific instance issue, can you completely uninstall the addon and reinstall it. I hope this should solve the issue which you might be facing.

**Comment by ineuw** [comment]
I did as you told me and now it works fine. Also tested the same FF version in Linux Mint and it's fine. Thanks for the quick reply.

**Comment by pratikabu** [comment]
Good to hear it helped.
I think there are some open issues which Firefox team is still looking at regarding the new WebExtension framework. Meanwhile we will have to do some hacks :)
