### ISSUE TITLE
Frequently unreponsisive website

### ISSUE THREAD

**Issue by DwardFarquard** [pratikabu/scrolltotop#75]
Your add-on is outstanding! However, it frequently becomes unresponsive on https://www.washingtonpost.com/

**Comment by pratikabu** [comment]
hi @DwardFarquard , i know it is quite late. But are you still facing any issues?
With my limited usage of washingtonpost.com I never faced any unresponsiveness.

**Comment by pratikabu** [comment]
Closing.
