### ISSUE TITLE
Conflict with other addon

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [pratikabu/scrolltotop#77]
I found this addon has a conflict with [Multi-touch Zoom](https://addons.mozilla.org/en-US/firefox/addon/multi-touch-zoom/). After installation, if I zoom in or zoom out with the pinch gesture on a trackpad, then the arrow is stucked on the webpage, not in set position. If I refresh the page, then rescale the page via `Ctrl` + `+` or `Ctrl` + `−`, then the problem is disappeared.

**Comment by pratikabu** [comment]
Do you've a way to get it fixed? I can't think of any.

**Comment by pratikabu** [comment]
Closing.
