### ISSUE TITLE
Freezes after returning to homepage

### ISSUE THREAD

**Issue by ghost** [pratikabu/scrolltotop#78]
Sir,

I have an issue with https://www.zerohedge.com/ . When I visit the homepage everything is working fine. Then when I click on an article everything still works fine. When I return to the homepage Scroll to Top freezes. None of the buttons work anymore. This is the only website sofar where I noticed this problem. I have tried to disable all my extensions and delete and install Scroll to Top anew, but with no result.

My OS is Ubuntu 18.04 with Firefox 62.0 (64 bits). I have tried it in Opera 55.0.2994.56 but there ZeroHedge works just fine. I add two screenshots of my settings of Scroll to Top.

Best regards,
Jan

![scroll to top-1](https://user-images.githubusercontent.com/43385685/45707012-f6292d80-bb7d-11e8-84a3-fee0cf5d5cd3.png)
![scroll to top-2](https://user-images.githubusercontent.com/43385685/45707013-f6292d80-bb7d-11e8-9c2d-a3ba3d513d79.png)

**Comment by pratikabu** [comment]
Hi, I did try to replicate this issue but was unable to replicate on the latest Firefox.
Is it something that you are still experiencing?

Though I did see another issue where the icons were not properly placed. Looks like issue with placement. I'll have to work on this one.

![image](https://user-images.githubusercontent.com/470973/76184939-c1f36380-619b-11ea-8804-577a3a942903.png)

**Comment by pratikabu** [comment]
Closing this issue as I've created a separate issue to handle the icon placements.
