### ISSUE TITLE
Update Options Page UI

### ISSUE THREAD

**Issue by pratikabu** [pratikabu/scrolltotop#80]
Update the Options Page UI so that it can be shown on the Chrome's extension page without opening a new tab for it.

For now Firefox and Opera doesn't work good with this so they will still open the options in a new tab but the UI will be new.

**Comment by KrasnayaPloshchad** [comment]
If you get bug fixes for #66 the options page will be fine on Android too.

**Comment by pratikabu** [comment]
good point @KrasnayaPloshchad, I'll see how does it look on a smaller real estate.

**Comment by pratikabu** [comment]
This is how the new UI looks like on a browser:

![image](https://user-images.githubusercontent.com/470973/50566737-9573ca00-0d02-11e9-8b4b-5ecd2f380609.png)

**Comment by pratikabu** [comment]
I've converted all the tables tags to div tags, will now have to write the CSS file for small screen devices. Will look into that next.

**Comment by pratikabu** [comment]
I've worked on making the Options page responsive with three width modes so far. I think I'll release a version update shortly. And pick anything else later.

pagesize > 750px
750px >= pagesize > 630px
630px >= pagesize

![image](https://user-images.githubusercontent.com/470973/57205735-38c13e00-6f86-11e9-9000-90d7374505ad.png)

![image](https://user-images.githubusercontent.com/470973/57205744-4971b400-6f86-11e9-9a20-3700cab5b4fb.png)

![image](https://user-images.githubusercontent.com/470973/57205751-58586680-6f86-11e9-9deb-f3c65275dbab.png)

**Comment by KrasnayaPloshchad** [comment]
Yeah. ✌️

**Comment by pratikabu** [comment]
The version for Firefox is now live and this issue is good to be closed now.
I'm releasing Chrome and Opera as well shortly.
