### ISSUE TITLE
Can the behaviour be like Yandex browser

### ISSUE THREAD

**Issue by jarun** [pratikabu/scrolltotop#85]
Yandex browser (Google Chrome based) let you just to the top of page when you left click on the tab. Left click again to return to where you were.

It's stupid simple and easy without any extra GUI buttons. Can this addon be made to behave the same way?

**Comment by jarun** [comment]
Not sure if this project is active anymore. Hence closing the issue.

**Comment by pratikabu** [comment]
hi @jarun,
I was busy with my office work and then for vacation. This behavior is not something that I want to provide by this addon. Also, I'm not sure if this behavior is even accepted on all the browsers that i support. Will look for it as part of my research for the next release. Though no promises.

Thanks
