### ISSUE TITLE
RFNF: third button to close the tab

### ISSUE THREAD

**Issue by QX7337** [pratikabu/scrolltotop#86]
Request For New Feature

i edited userChrome.css to 'hide' the button for closing the tab. so i can use the valuable space over there to display the name of the tab.  this makes closing the tab a little more difficult.  but it's worth it.  i hope you can add an option to show a third button to close the tab

thank you

peter

**Comment by pratikabu** [comment]
Hi That's an interesting ask. Let me think about it. Instead of giving another button, how about giving an option to choose from whether to use existing X button to remove the addon or close the tab?

**Comment by pratikabu** [comment]
I'm sorry but since Chrome and Firefox wants single clear responsibility from an addon. I may not be able to add this functionality. Thanks for patience, closing this issue.
