### ISSUE TITLE
Icon disappears when clicked instead of scrolling up

### ISSUE THREAD

**Issue by DanielBeadle** [pratikabu/scrolltotop#93]
With the latest version, I'm experiencing a glitch wherein clicking on the icon simply makes it disappear rather than scrolling up. Happens on Twitter and YouTube, possibly more.

Using Chrome Version 80.0.3987.132 (latest as of 3/14/20).

Anyone else seeing this?

**Comment by pratikabu** [comment]
I tested all the sites that you've mentioned and it works great without issue. I'm on the same browser version as well (80.0.3987.132).
Also, the only change that is present in this release is to add `display: block` which was default on these sites anyway.

I'm suspecting some other addon might be conflicting on your browser.

**Comment by DanielBeadle** [comment]
Thank you, I'll disable extensions to find the problem.

**Comment by Jamesstevens-3rd** [comment]
Daniel
I have the same issue on waterfox classic on windows 8.1 pro and 10 pro 

workaround: change the Control Options to Simple and restart the browser

hope that helps

**Comment by DanielBeadle** [comment]
Disabling my extensions did nothing, so this is a good fix, thanks. Not that I need those Control Options, but I'll live with it for now.

**Comment by pratikabu** [comment]
That’s strange but good that it has a solution.
Unless I’m able to replicate it will be hard to fix.

**Comment by Jamesstevens-3rd** [comment]
this text file contains my settings export that has the problem, I was using 4.8.0.2 ok until I updated to 4.8.1 

[New.txt](https://github.com/pratikabu/scrolltotop/files/4361513/New.txt)

**Comment by pratikabu** [comment]
The above mentioned settings configuration works great on my Chrome browser.

**Comment by drlifeng** [comment]
I have the same problem. Using  firefox V74 with addon version 4.8.1,when I downgrade  to  the version 4.8.0.2 everything is ok .

**Comment by pratikabu** [comment]
hi @drlifeng, what website are you seeing this issue on?
Also what operating system are you on?

**Comment by drlifeng** [comment]
> hi @drlifeng, what website are you seeing this issue on?
> Also what operating system are you on?

mostly twitter ,sometime other website(163.com).
operating system  linux mint 19.3

**Comment by pratikabu** [comment]
> mostly twitter ,sometime other website(163.com).
> operating system linux mint 19.3

That's very strange. I installed Linux Mint 19 version and downloaded Firefox 74 and tried replicating the issue but unable to. :(

**Comment by drlifeng** [comment]
> > mostly twitter ,sometime other website(163.com).
> > operating system linux mint 19.3
> 
> That's very strange. I installed Linux Mint 19 version and downloaded Firefox 74 and tried replicating the issue but unable to. :(

The bug will not happen immediately, I feel it is randomly. 
Or it is incompatible with other addons and userscripts .
Fortunately  v4.8.0.2 works very well.
Thank you for reply !

**Comment by Jacosci** [comment]
Can confirm it's been happening to me as well with Firefox 74.0 64-bit on Windows 10.
Problem starting to occur when "Control Options" is set to "none" and it happens only when I click certain spot of the STT icon. Also occasionally it causes STT preference page being opened despite I use the aforementioned setting.
As far as I'm aware this happens on all kind of sites. I think it just requires specific trigger to make it happen but I still can't conclusively say what it is.

**Comment by Chocapic** [comment]
Same issue, last version of chrome, sometime the arrow randomly disappear instead of scrolling up. Happens mostly on reddit. Using single big arrow and none "control option"

**Comment by pratikabu** [comment]
Hi All,

I can confirm that I was able to replicate this issue and I'll be releasing a fix for it shortly.
The issue only happens when you select "None" in the Control Options.

Thanks
Pratik

**Comment by pratikabu** [comment]
Hi All,

The issue has been fixed and I'll release a new version soon along with other fixes/enhancements.
See PR #107 to see code fixes.
See [4.8.5 Milestone](https://github.com/pratikabu/scrolltotop/milestone/9) to see new changes coming shortly.

I'll be closing this issue, kindly comment with your observations.

Thanks
Pratik

**Comment by pratikabu** [comment]
I’ve submitted the new version to all respective browser galleries. Firefox is already available, Chrome and Opera should be available soon.

Thanks
